import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import MasterHead from "../components/masterhead";
import AboutUs from "../components/about-us";
import Skills from "../components/skills";
import Works from "../components/works";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Solvevolve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MasterHead />
      <AboutUs />
      <Skills />
      {/* <AboutUs /> */}
      <Works />
    </div>
  );
};

export default Home;
